// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc_members

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MembersMembersTable struct {
	ID       int64
	Name     string
	Birthday pgtype.Date
}
