// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc_members

import (
	"database/sql"
)

type MembersMembersTable struct {
	ID       int64
	Name     string
	Birthday sql.NullTime
}
