// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc_members

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMember(ctx context.Context, db DBTX, arg *CreateMemberParams) (*MembersMembersTable, error)
	DeleteMember(ctx context.Context, db DBTX, id int64) (*MembersMembersTable, error)
	GetMember(ctx context.Context, db DBTX, id int64) (*MembersMembersTable, error)
	GetMembersList(ctx context.Context, db DBTX, name pgtype.Text) ([]*MembersMembersTable, error)
	UpdateMember(ctx context.Context, db DBTX, arg *UpdateMemberParams) (*MembersMembersTable, error)
}

var _ Querier = (*Queries)(nil)
